avcodec: Remove FF_API_PARSER_PRIVATE for ffmpeg 9.0
avcodec: Remove FF_API_PARSER_PRIVATE
Deprecated on 2025-11-01. It is removed right now despite
this being fairly recently, because users never had
a legitimate reason to touch these fields at all:
After all, their meaning was entirely undocumented.

Furthermore, the split callback is unset for any parser
since commit e5af920 from 2021.
https://github.com/FFmpeg/FFmpeg/commit/e967ae98f404aca912a80f014e6473276804235f#diff-f8a1a6e895ad6e9ecbb76ae94fb2efd313428125caa8403a88af174cd791fc21
```
lwindex.c: In function 'get_index_helper':
lwindex.c:1110:76: error: 'const struct AVCodecParser' has no member named 'split'
 1110 |                 && helper->parser_ctx->parser && helper->parser_ctx->parser->split
      |                                                                            ^~
lwindex.c:1111:46: error: 'const struct AVCodecParser' has no member named 'split'
 1111 |                 && helper->parser_ctx->parser->split(helper->codec_ctx, codecpar->extradata + 8, codecpar->extradata_size - 8) <= 0) {
      |                                              ^~
lwindex.c: In function 'append_extradata_if_new':
lwindex.c:1291:35: error: 'const struct AVCodecParser' has no member named 'split'
 1291 |             if (parser_ctx->parser->split) {
      |                                   ^~
lwindex.c:1296:74: error: 'const struct AVCodecParser' has no member named 'split'
 1296 |                 int extradata_size = helper->bsf ? 0 : parser_ctx->parser->split(ctx, pkt->data, pkt->size);
      |                                                                          ^~
```