avcodec: Remove FF_API_V410_CODECID
avcodec: Remove FF_API_V408_CODECID
Deprecated on 2024-10-12.
The output of the v410enc test changes because padding bits
are now filled with 1s instead of zeroes and because
bits_per_coded_sample changes to 30 (from 32), see
https://github.com/FFmpeg/FFmpeg/commit/0438966d84deb34394df1929a53ab79fee5cc8d4
```
libavsmash.c:244:46: error: 'AV_CODEC_ID_V410' undeclared (first use in this function); did you mean 'AV_CODEC_ID_V210'?
  244 |         ELSE_IF_GET_CODEC_ID_FROM_CODEC_TYPE(AV_CODEC_ID_V410, QT_CODEC_TYPE_V410_VIDEO);
      |                                              ^~~~~~~~~~~~~~~~
libavsmash.c:193:81: note: in definition of macro 'ELSE_IF_GET_CODEC_ID_FROM_CODEC_TYPE'
  193 |     else if (lsmash_check_codec_type_identical(sample_type, codec_type)) return codec_id
      |                                                                                 ^~~~~~~~
```